config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  devise_for :users
  resources :users, only: [:index, :show]
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'

  resources :books, only: [:create, :index, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  private

  def after_sign_in_path_for(resources_or_scope)
    user_path(current_user.id)
  end

  def after_sign_up_path_for(resources_or_scope)
    user_path(current_user.id)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      redirect_to books_path, flash: { count: @book.errors.count, messages: @book.errors.full_messages }
    end
  end

  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
    @books = Book.all
  end

  def show
    @users = User.all
    @user = User.find(current_user.id)
    @new_book = Book.new
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_back(fallback_location: books_path)
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      redirect_to book_path(@book), flash: {
        count: @book.errors.count,
        messages: @book.errors.full_messages,
        input_title: book_params[:title],
        input_body: book_params[:body],
      }
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @users = User.all
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_back(fallback_location: user_path(current_user))
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      redirect_to user_path(@user), flash: { count: @user.errors.count, messages: @user.errors.full_messages, input_name: user_params[:name] }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<div class="container margin-top">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
      <% if flash[:count] %>
        <div class="error_explanation">
          <h3><%= flash[:count] %>  error prohibited this obj from being saved:</h3>
          <ul>
            <% flash[:messages].each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @book, url: "/books/#{@book.id}", local: true do |f| %>
      <div class="form-group">
        <label for="book_title">Title</label>
        <%= f.text_field :title, class: "form-control" %>
      </div>
      <div class="form-group">
        <label for="book_opinion">Opinion</label>
        <%= f.text_area :body, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Update Book', class: "btn btn-success" %>
      </div>
      <% end %>
      <%= link_to "Show", book_path(@book) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0 margin-top">
  <% if flash[:count] %>
    <div class="error_explanation">
      <h3><%= flash[:count] %>  error prohibited this obj from being saved:</h3>
      <ul>
        <% flash[:messages].each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "100x100" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <a class="btn btn-outline-secondary btn-block user-edit-btn" href="/users/<%= @user.id %>/edit">
          <i class="fas fa-user-cog"></i>
        </a>
      </div>
      <%= render 'component/new_book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <% @users.each do |user| %>
              <% if book.user_id == user.id %>
                <td>
                  <a href="/users/<%= user.id %>">
                    <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
                  </a>
                </td>
              <% end %>
            <% end %>
            <td><%= link_to "#{book.title}", book_path(book) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:count] %>
  <div class="container margin-top">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h1>Editing Book</h1>
          <div class="error_explanation">
            <h3><%= flash[:count] %>  error prohibited this obj from being saved:</h3>
            <ul>
              <% flash[:messages].each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <%= form_with model: @book, url: "/books/#{@book.id}", local: true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control", value: "#{flash[:input_title]}" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control", value: "#{flash[:input_body]}" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update Book', class: "btn btn-success" %>
        </div>
        <% end %>
        <%= link_to "Show", book_path(@book) %>
        |
        <%= link_to "Back", books_path %>
      </div>
    </div>
  </div>
<% else %>
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <div class="container margin-top">
    <div class="row">
      <div class="col-md-3">
        <h2>User info</h2>
        <% @users.each do |user| %>
          <% if user.id == @book.user_id %>
            <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100" %>
            <table class="table">
              <tbody>
                <tr></tr>
                <tr>
                  <th>name</th>
                  <th><%= user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= user.introduction %></th>
                </tr>
              </tbody>
            </table>
            <div class="row">
              <a class="btn btn-outline-secondary btn-block user-edit-btn" href="/users/<%= user.id %>/edit">
                <i class="fas fa-user-cog"></i>
              </a>
            </div>
          <% end %>
        <% end %>
        <%= render 'component/new_book', book: @new_book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Book detail</h2>
        <table class="table">
          <tbody>
            <tr>
              <td>
                <% @users.each do |user| %>
                  <% if @book.user_id == user.id %>
                    <a href="/users/<%= user.id %>">
                      <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
                      <br>
                      <%= user.name %>
                    </a>
                  <% end %>
                <% end %>
              </td>
              <td>
                <%= link_to "#{@book.title}", book_path(@book) %>
              </td>
              <td>
                <%= @book.body %>
              </td>
              <% if @user.id == @book.user_id %>
                <td>
                  <%= link_to "Edit", edit_book_path(@book), class: "btn btn-sm btn-success" %>
                </td>
                <td>
                  <%= link_to "Destroy", book_path(@book), method: :delete, data: { confirm: "本当に消しますか？" }, class: "btn btn-sm btn-danger" %>
                </td>
              <% end %>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>

app/views/component/_new_book.html.erb
<h2 class="mt-3">New book</h2>
<%= form_with model: book, url: "/books", local: true do |f| %>
<div class="form-group">
  <label for="book_title">Title</label>
  <%= f.text_field :title, class: "form-control" %>
</div>
<div class="form-group">
  <label for="book_opinion">Opinion</label>
  <%= f.text_area :body, class: "form-control" %>
</div>
<div class="form-group">
  <%= f.submit 'Create Book', class: "btn btn-success" %>
</div>
<% end %>

app/views/component/_user_info.html.erb
<h2>User info</h2>
<%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100" %>
<table class="table">
  <tbody>
    <tr></tr>
    <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
      <th><%= user.introduction %></th>
    </tr>
  </tbody>
</table>
<div class="row">
  <a class="btn btn-outline-secondary btn-block user-edit-btn" href="/users/<%= user.id %>/edit">
    <i class="fas fa-user-cog"></i>
  </a>
</div>

app/views/homes/about.html.erb
<div class="container">
  <div class="row">
    <h1 class="px-3 mx-auto top-title">
      Welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!
    </h1>
  </div>
</div>

app/views/homes/top.html.erb
<% if flash[:notice] %>
  <p class="notice"><%= flash[:notice] %></p>
<% end %>
<div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1 class="top-title">welcome to <i class="fas fa-book"></i><strong>Bookers</strong> !!</h1>
      <p>In <i class="fas fa-book"></i><strong>Bookers,</strong></p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="col-10 mx-auto">
        <%= link_to "Log in", new_user_session_path, class: "btn btn-info btn-lg btn-block top-btn-group" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-lg btn-block top-btn-group" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/901e69fcae.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <%= link_to "Bookers", root_path, class: "navbar-brand margin-left" %>
        <button class="navbar-toggler margin-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse margin-right" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="nav-item active">
                <%= link_to " Home", user_path(current_user), class: "fas fa-home nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " Users", users_path, class: "fas fa-users nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " Books", books_path, class: "fas fa-book-open nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " logout", destroy_user_session_path, class: "fas fa-sign-out-alt nav-link text-light", method: :delete %>
              </li>
            <% else %>
              <li class="nav-item active">
                <%= link_to " Home", root_path, class: "fas fa-home nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " About", home_about_path, class: "fas fa-link nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " sign up", new_user_registration_path, class: "fas fa-user-plus nav-link text-light" %>
              </li>
              <li class="nav-item">
                <%= link_to " login", new_user_session_path, class: "fas fa-sign-in-alt nav-link text-light" %>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
    <footer>
      <div class="container mt-5">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/edit.html.erb
<div class="container margin-top">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>User info</h2>
      <% if flash[:count] %>
        <div class="error_explanation">
          <h3><%= flash[:count] %>  error prohibited this obj from being saved:</h3>
          <ul>
            <% flash[:messages].each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_with model: @user, url: "/users/#{@user.id}", local: true do |f| %>
      <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class: "form-control" %>
      </div>
      <div class="form_-group user-image">
        <label for="user_image">Image</label>
        <%= f.attachment_field :profile_image, class: "form-control-file" %>
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.submit 'Update User', class: "btn btn-secondary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0 margin-top">
  <div class="row">
    <div class="col-md-3">
      <%= render 'component/user_info', user: @user %>
      <%= render 'component/new_book', book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %></td>
              <td><%= user.name %></td>
              <td><%= link_to "Show", user_path(user) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:count] %>
  <div class="container margin-top">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
        <h2>User info</h2>
          <div class="error_explanation">
            <h3><%= flash[:count] %>  error prohibited this obj from being saved:</h3>
            <ul>
              <% flash[:messages].each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <%= form_with model: @user, url: "/users/#{@user.id}", local: true do |f| %>
        <div class="form-group">
          <label for="user_name">Name</label>
          <%= f.text_field :name, class: "form-control", value: "#{flash[:input_name]}" %>
        </div>
        <div class="form_-group user-image">
          <label for="user_image">Image</label>
          <%= f.attachment_field :profile_image, class: "form-control-file" %>
        </div>
        <div class="form-group">
          <label for="user_introduction">Introduction</label>
          <%= f.text_area :introduction, class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit 'Update User', class: "btn btn-secondary" %>
        </div>
        <% end %>
      </div>
    </div>
  </div
<% else %>
  <% if flash[:notice] %>
    <p class="notice"><%= flash[:notice] %></p>
  <% end %>
  <div class="container px-5 px-sm-0 margin-top">
    <div class="row">
      <div class="col-md-3">
        <%= render 'component/user_info', user: @user %>
        <%= render 'component/new_book', book: @book %>
      </div>
      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>
        <table class="table">
          <thead>
            <tr>
              <th></th>
              <th>Title</th>
              <th>Opinion</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
          <% @books.each do |book| %>
            <tr>
              <% @users.each do |user| %>
                <% if book.user_id == user.id %>
                  <td>
                    <a href="/users/<%= user.id %>">
                      <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40" %>
                    </a>
                  </td>
                <% end %>
              <% end %>
              <td><%= link_to book.title, book_path(book) %></td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
<% end %>